--------------------------------------------------------
--  File created - Monday-November-04-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SERVICE
--------------------------------------------------------

  CREATE TABLE "AYMEN"."SERVICE" 
   (	"IDM" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"PRICE" FLOAT(126), 
	"DURATION" VARCHAR2(20 BYTE), 
	"EMPLOYEE" VARCHAR2(20 BYTE), 
	"EQUIPEMENT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into AYMEN.SERVICE
SET DEFINE OFF;
Insert into AYMEN.SERVICE (IDM,NAME,DESCRIPTION,PRICE,DURATION,EMPLOYEE,EQUIPEMENT) values (2,'aymenn','raddedi',3,'3','e','az');
Insert into AYMEN.SERVICE (IDM,NAME,DESCRIPTION,PRICE,DURATION,EMPLOYEE,EQUIPEMENT) values (1,'ahmed','dfgh',77,'fgh','gh','fgh');
--------------------------------------------------------
--  DDL for Index SERVICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AYMEN"."SERVICE_PK" ON "AYMEN"."SERVICE" ("IDM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SERVICE
--------------------------------------------------------

  ALTER TABLE "AYMEN"."SERVICE" ADD CONSTRAINT "SERVICE_PK" PRIMARY KEY ("IDM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AYMEN"."SERVICE" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."SERVICE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "AYMEN"."SERVICE" MODIFY ("IDM" NOT NULL ENABLE);
